# Generated by Django 5.0 on 2024-01-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('lostlocation', models.CharField(max_length=100)),
                ('foundlocation', models.CharField(max_length=100)),
                ('lostdate', models.DateTimeField(max_length=100)),
                ('founddate', models.DateTimeField(max_length=100)),
            ],
        ),
    ]
