# Generated by Django 5.0 on 2024-03-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0006_alter_article_founddate_alter_article_lostdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='create_date',
        ),
        migrations.AlterField(
            model_name='article',
            name='lostlocation',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
