# Generated by Django 5.0 on 2024-03-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0007_remove_article_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
