# Generated by Django 5.0 on 2024-03-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0009_alter_article_founddate_alter_article_foundlocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='founddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='lostdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='lostlocation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
