# Generated by Django 5.0 on 2024-03-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0010_alter_article_founddate_alter_article_lostdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='founddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='lostdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
