# Generated by Django 5.0 on 2024-04-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0011_alter_article_founddate_alter_article_lostdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='founddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='foundlocation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='lostdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='lostlocation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
