# Generated by Django 5.0 on 2024-04-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
